"""GENERATED by sim/configurator.py from sim/robot.toml - edit that file instead."""

# Joint-space degrees: 0 = the straight pose described in robot.toml.
NUM_JOINTS = 6
JOINT_NAMES = ['base_yaw', 'shoulder_pitch', 'elbow_pitch', 'wrist_pitch', 'wrist_yaw', 'head_roll']
JOINT_MIN = [-120, -60, -120, -90, -90, -45]
JOINT_MAX = [120, 90, 120, 90, 90, 45]
HOME = [0, -10, 70, -60, 0, 0]

MAX_SPEED_DEG_S = 120
CONTROL_HZ = 50
