"""Robot configurator: sim/robot.toml -> MuJoCo model + constants for the sketch and app.

    python sim/configurator.py

Outputs:
    sim/build/robot.xml                            MuJoCo model (open it with sim/view.py)
    apps/expressive_robot/sketch/robot_config.h    joint limits, home pose, speed for the sketch
    apps/expressive_robot/python/robot_config.py   the same values for the app's Python
"""

import math
import tomllib
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "sim" / "robot.toml"
MJCF_PATH = ROOT / "sim" / "build" / "robot.xml"
APP_DIR = ROOT / "apps" / "expressive_robot"
HEADER_PATH = APP_DIR / "sketch" / "robot_config.h"
PY_CONFIG_PATH = APP_DIR / "python" / "robot_config.py"

AXES = {"x": [1, 0, 0], "y": [0, 1, 0], "z": [0, 0, 1]}
JOINT_DEFAULTS = {
    "mass": 0.05,
    "radius": 0.012,
    "kp": 20.0,
    "damping": 0.5,
    "armature": 0.001,
    "max_torque": None,
    "home": 0.0,
}
GENERATED_NOTE = "GENERATED by sim/configurator.py from sim/robot.toml - edit that file instead."


def load_config(path=CONFIG_PATH):
    with open(path, "rb") as f:
        cfg = tomllib.load(f)

    defaults = {**JOINT_DEFAULTS, **cfg.get("defaults", {})}
    joints, names = [], set()
    for i, raw in enumerate(cfg.get("joint", [])):
        j = {**defaults, **raw}
        where = f"joint #{i + 1} ({j.get('name', 'unnamed')})"
        for key in ("name", "axis", "range", "link"):
            if key not in j:
                raise ValueError(f"{where}: missing '{key}'")
        if j["name"] in names:
            raise ValueError(f"{where}: duplicate name")
        names.add(j["name"])

        axis = AXES[j["axis"]] if isinstance(j["axis"], str) else j["axis"]
        norm = math.dist(axis, [0, 0, 0])
        if norm == 0:
            raise ValueError(f"{where}: axis is zero")
        j["axis"] = [a / norm for a in axis]

        lo, hi = j["range"]
        if not lo <= j["home"] <= hi:
            raise ValueError(f"{where}: home {j['home']} outside range {j['range']}")
        if j["mass"] <= 0:
            raise ValueError(f"{where}: mass must be > 0")
        joints.append(j)

    if not joints:
        raise ValueError("robot.toml has no [[joint]] entries")
    cfg["joint"] = joints
    cfg.setdefault("motion", {}).setdefault("max_speed_deg_s", 120)
    cfg["motion"].setdefault("control_hz", 50)
    return cfg


def fmt(values):
    return " ".join(f"{v:.6g}" for v in values)


def build_mjcf(cfg):
    root = ET.Element("mujoco", model=cfg.get("name", "robot"))
    ET.SubElement(root, "compiler", angle="radian", autolimits="true")
    ET.SubElement(root, "option", timestep="0.002")

    asset = ET.SubElement(root, "asset")
    ET.SubElement(asset, "texture", name="grid", type="2d", builtin="checker",
                  rgb1=".25 .28 .32", rgb2=".18 .2 .24", width="512", height="512")
    ET.SubElement(asset, "material", name="grid", texture="grid", texrepeat="10 10")
    ET.SubElement(asset, "material", name="link", rgba=".85 .85 .88 1")
    ET.SubElement(asset, "material", name="axis", rgba=".95 .55 .1 1")
    ET.SubElement(asset, "material", name="head", rgba=".3 .55 .9 1")
    ET.SubElement(asset, "material", name="eye", rgba=".05 .05 .05 1")

    # Kinematics only: no collisions anywhere, so overlapping links never push on each other.
    default = ET.SubElement(root, "default")
    ET.SubElement(default, "geom", contype="0", conaffinity="0")

    world = ET.SubElement(root, "worldbody")
    ET.SubElement(world, "light", pos="0 -0.5 1.5", dir="0 0.3 -1", diffuse=".8 .8 .8")
    ET.SubElement(world, "geom", name="floor", type="plane", size="1 1 0.01", material="grid")

    base = cfg.get("base", {})
    bw, bd, bh = base.get("size", [0.1, 0.1, 0.03])
    parent = ET.SubElement(world, "body", name="base")
    ET.SubElement(parent, "geom", type="box", size=fmt([bw / 2, bd / 2, bh / 2]),
                  pos=fmt([0, 0, bh / 2]), mass=f"{base.get('mass', 0.5):g}", material="link")
    pos = [0, 0, bh]

    actuators = []
    for j in cfg["joint"]:
        body = ET.SubElement(parent, "body", name=j["name"], pos=fmt(pos))
        ET.SubElement(body, "joint", name=j["name"], type="hinge", axis=fmt(j["axis"]),
                      range=fmt(map(math.radians, j["range"])),
                      damping=f"{j['damping']:g}", armature=f"{j['armature']:g}")

        # Orange stub along the rotation axis, so you can see which way each joint turns.
        stub = [a * 0.025 for a in j["axis"]]
        ET.SubElement(body, "geom", type="cylinder", fromto=fmt([-s for s in stub] + stub),
                      size=f"{j['radius'] * 1.4:g}", mass="0", material="axis")

        if math.dist(j["link"], [0, 0, 0]) > 1e-6:
            ET.SubElement(body, "geom", type="capsule", fromto=fmt([0, 0, 0] + j["link"]),
                          size=f"{j['radius']:g}", mass=f"{j['mass']:g}", material="link")
        else:  # joints stacked at the same point: a small sphere carries the mass
            ET.SubElement(body, "geom", type="sphere", size=f"{j['radius']:g}",
                          mass=f"{j['mass']:g}", material="link")

        actuator = {"name": j["name"], "joint": j["name"], "kp": f"{j['kp']:g}",
                    "ctrlrange": fmt(map(math.radians, j["range"]))}
        if j["max_torque"] is not None:
            actuator["forcerange"] = fmt([-j["max_torque"], j["max_torque"]])
        actuators.append(actuator)
        parent, pos = body, j["link"]

    # Head: a box with two eyes on its +x face, welded to the last link.
    head = cfg.get("head", {})
    hx, hy, hz = [s / 2 for s in head.get("size", [0.06, 0.08, 0.05])]
    head_body = ET.SubElement(parent, "body", name="head", pos=fmt([pos[0], pos[1], pos[2] + hz]))
    ET.SubElement(head_body, "geom", type="box", size=fmt([hx, hy, hz]),
                  mass=f"{head.get('mass', 0.1):g}", material="head")
    for side in (-1, 1):
        ET.SubElement(head_body, "geom", type="sphere", size=f"{min(hy, hz) * 0.18:g}",
                      pos=fmt([hx, side * hy * 0.45, hz * 0.25]), mass="0", material="eye")

    actuator_el = ET.SubElement(root, "actuator")
    for a in actuators:
        ET.SubElement(actuator_el, "position", **a)

    home = [math.radians(j["home"]) for j in cfg["joint"]]
    keyframe = ET.SubElement(root, "keyframe")
    ET.SubElement(keyframe, "key", name="home", qpos=fmt(home), ctrl=fmt(home))

    ET.indent(root)
    return f"<!-- {GENERATED_NOTE} -->\n" + ET.tostring(root, encoding="unicode") + "\n"


def build_header(cfg):
    joints = cfg["joint"]

    def floats(key):
        return ", ".join(f"{j[key]:g}" for j in joints)

    names = ", ".join(f'"{j["name"]}"' for j in joints)
    motion = cfg["motion"]
    return f"""// {GENERATED_NOTE}
#pragma once

// Joint-space degrees: 0 = the straight pose described in robot.toml.
const int NUM_JOINTS = {len(joints)};
const char* const JOINT_NAMES[NUM_JOINTS] = {{{names}}};
const float JOINT_MIN[NUM_JOINTS] = {{{", ".join(f"{j['range'][0]:g}" for j in joints)}}};
const float JOINT_MAX[NUM_JOINTS] = {{{", ".join(f"{j['range'][1]:g}" for j in joints)}}};
const float HOME[NUM_JOINTS] = {{{floats("home")}}};

const float MAX_SPEED_DEG_S = {motion["max_speed_deg_s"]:g};
const unsigned long CONTROL_PERIOD_MS = {round(1000 / motion["control_hz"])};
"""


def build_py_config(cfg):
    joints = cfg["joint"]
    motion = cfg["motion"]
    return f'''"""{GENERATED_NOTE}"""

# Joint-space degrees: 0 = the straight pose described in robot.toml.
NUM_JOINTS = {len(joints)}
JOINT_NAMES = {[j["name"] for j in joints]!r}
JOINT_MIN = {[j["range"][0] for j in joints]!r}
JOINT_MAX = {[j["range"][1] for j in joints]!r}
HOME = {[j["home"] for j in joints]!r}

MAX_SPEED_DEG_S = {motion["max_speed_deg_s"]!r}
CONTROL_HZ = {motion["control_hz"]!r}
'''


def write_if_changed(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def generate(config_path=CONFIG_PATH, verbose=True):
    """Rebuild every output from robot.toml. Returns (config, path to the MuJoCo model)."""
    cfg = load_config(config_path)
    outputs = {
        MJCF_PATH: build_mjcf(cfg),
        HEADER_PATH: build_header(cfg),
        PY_CONFIG_PATH: build_py_config(cfg),
    }
    for path, text in outputs.items():
        changed = write_if_changed(path, text)
        if verbose:
            print(f"  {'wrote' if changed else 'unchanged'}  {path.relative_to(ROOT)}")
    return cfg, MJCF_PATH


if __name__ == "__main__":
    cfg, _ = generate()
    print(f"{cfg.get('name', 'robot')}: {len(cfg['joint'])} joints "
          f"({', '.join(j['name'] for j in cfg['joint'])})")
