// GENERATED by sim/configurator.py from sim/robot.toml - edit that file instead.
#pragma once

// Joint-space degrees: 0 = the straight pose described in robot.toml.
const int NUM_JOINTS = 6;
const char* const JOINT_NAMES[NUM_JOINTS] = {"base_yaw", "shoulder_pitch", "elbow_pitch", "wrist_pitch", "wrist_yaw", "head_roll"};
const float JOINT_MIN[NUM_JOINTS] = {-120, -60, -120, -90, -90, -45};
const float JOINT_MAX[NUM_JOINTS] = {120, 90, 120, 90, 90, 45};
const float HOME[NUM_JOINTS] = {0, -10, 70, -60, 0, 0};

const float MAX_SPEED_DEG_S = 120;
const unsigned long CONTROL_PERIOD_MS = 20;
