"""Clip player: keyframes -> dense joint trajectory at the control rate.

    traj = play(load_clip("nod_yes/medium"), robot, start=robot.home, amplitude=1.2)
    traj.t, traj.q   # (N,) seconds, (N, joints) degrees

Clip format (motion_lib/clips/<name>__<variant>.json, generated by author.py):
    mode         "additive": keyframe values are offsets from the start pose (plays from anywhere)
                 "absolute": keyframe values are joint angles; starts at entry_pose, ends at exit_pose
    joint_mask   joints the clip moves; every other joint holds its start value
    keyframes    [{t, joints: {name: deg}, ease, peak?}]. A keyframe may list only some joints;
                 each joint follows its own keyframes, which allows follow-through offsets.
                 `ease` shapes the segment arriving at the keyframe:
                 linear | ease_in | ease_out | ease_in_out (quintic, zero vel/accel at ends)
                 | cubic (smooth Catmull-Rom curve through neighbouring cubic keyframes)
    params       amplitude (scales the motion around the straight start->end line, so entry
                 and exit poses never move), time_scale (duration multiplier: 2.0 = twice as
                 slow), hold (extra seconds at the keyframe marked `peak`)
"""

import json
import math
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

CLIPS_DIR = Path(__file__).parent / "clips"


def _quintic(s):
    return s * s * s * (s * (6 * s - 15) + 10)


EASES = {
    "linear": lambda s: s,
    "ease_in": lambda s: s ** 3,
    "ease_out": lambda s: 1 - (1 - s) ** 3,
    "ease_in_out": _quintic,
}
VALID_EASES = set(EASES) | {"cubic"}


@dataclass
class Trajectory:
    t: np.ndarray  # (N,) seconds, uniform at 1 / rate
    q: np.ndarray  # (N, joints) degrees
    joint_names: list
    events: list = field(default_factory=list)  # [{t, light: brightness}, ...]
    marks: list = field(default_factory=list)  # [(t_start, t_end, label), ...] for plots

    @property
    def dt(self):
        return self.t[1] - self.t[0] if len(self.t) > 1 else 0.0

    @property
    def duration(self):
        return float(self.t[-1])

    def then(self, other):
        """This trajectory followed by `other` (which must start where this one ends)."""
        offset = self.t[-1] + self.dt
        shift = lambda items: [(a + offset, b + offset, label) for a, b, label in items]  # noqa: E731
        return Trajectory(
            np.concatenate([self.t, other.t + offset]),
            np.vstack([self.q, other.q]),
            self.joint_names,
            self.events + [{**e, "t": e["t"] + offset} for e in other.events],
            self.marks + shift(other.marks),
        )


# --- clips on disk -----------------------------------------------------------------


def clip_path(ref):
    name, _, variant = ref.partition("/")
    return CLIPS_DIR / f"{name}__{variant}.json"


def load_clip(ref):
    """Load by reference ("nod_yes/medium") or by file path."""
    path = Path(ref) if str(ref).endswith(".json") else clip_path(ref)
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def list_clips():
    return sorted(p.stem.replace("__", "/") for p in CLIPS_DIR.glob("*.json"))


def ref(clip):
    return f"{clip['name']}/{clip['variant']}"


# --- interpolation -----------------------------------------------------------------


def _interpolate(times, values, eases, t):
    """One joint's curve through its keyframes, sampled at times t."""
    n = len(times)
    tangents = np.zeros(n)
    for i in range(1, n - 1):
        if eases[i] == "cubic" and eases[i + 1] == "cubic":
            tangents[i] = (values[i + 1] - values[i - 1]) / (times[i + 1] - times[i - 1])

    out = np.full(len(t), values[0], float)
    for i in range(1, n):
        t0, t1 = times[i - 1], times[i]
        sel = (t > t0) & (t <= t1) if i > 1 else (t >= t0) & (t <= t1)
        if not sel.any() or t1 <= t0:
            continue
        h = t1 - t0
        s = (t[sel] - t0) / h
        v0, v1 = values[i - 1], values[i]
        if eases[i] == "cubic":
            m0, m1 = tangents[i - 1] * h, tangents[i] * h
            s2, s3 = s * s, s * s * s
            out[sel] = ((2 * s3 - 3 * s2 + 1) * v0 + (s3 - 2 * s2 + s) * m0
                        + (-2 * s3 + 3 * s2) * v1 + (s3 - s2) * m1)
        else:
            out[sel] = v0 + (v1 - v0) * EASES[eases[i]](s)
    out[t > times[-1]] = values[-1]
    return out


def _resolve_params(clip, amplitude, time_scale, hold, enforce_ranges):
    params = clip.get("params", {})
    resolved = {}
    for key, value in (("amplitude", amplitude), ("time_scale", time_scale), ("hold", hold)):
        spec = params.get(key, {})
        value = spec.get("default", 0.0 if key == "hold" else 1.0) if value is None else value
        lo, hi = spec.get("range", (value, value))
        if enforce_ranges and not lo - 1e-9 <= value <= hi + 1e-9:
            raise ValueError(f"{ref(clip)}: {key}={value} outside validated range [{lo}, {hi}]")
        resolved[key] = value
    return resolved


def _peak_index(kfs):
    for i, k in enumerate(kfs):
        if k.get("peak"):
            return i
    return max(range(len(kfs)), key=lambda i: max((abs(v) for v in kfs[i]["joints"].values()), default=0))


def _timed_keyframes(clip, time_scale, hold, repeat):
    kfs = [dict(k, joints=dict(k["joints"])) for k in clip["keyframes"]]
    if repeat > 1:
        if not clip.get("loopable"):
            raise ValueError(f"{ref(clip)} is not loopable")
        period = kfs[-1]["t"]
        loop = [k for k in kfs if k["t"] > 0]
        for r in range(1, repeat):
            kfs += [dict(k, t=k["t"] + r * period, peak=False) for k in loop]
    for k in kfs:
        k["t"] *= time_scale
    if hold > 0:
        peak = _peak_index(kfs)
        t_peak = kfs[peak]["t"]
        for k in kfs:
            if k["t"] > t_peak:
                k["t"] += hold
        kfs.insert(peak + 1, {"t": t_peak + hold, "joints": dict(kfs[peak]["joints"]), "ease": "linear"})
    return kfs


def play(clip, robot, start=None, amplitude=None, time_scale=None, hold=None, repeat=1,
         enforce_ranges=True):
    """Dense trajectory for one clip.

    start: pose to play from. Additive clips default to home; absolute clips to their
    entry pose, and refuse a start farther than pose_tolerance_deg from it (null entry
    pose = plays from anywhere, e.g. `home`).
    """
    p = _resolve_params(clip, amplitude, time_scale, hold, enforce_ranges)
    additive = clip["mode"] == "additive"
    names = robot.joint_names

    if start is None:
        entry = clip.get("entry_pose")
        start = robot.home if additive or entry is None else [entry[n] for n in names]
    start = np.asarray(start, float)
    if not additive and clip.get("entry_pose"):
        entry = np.array([clip["entry_pose"][n] for n in names])
        err = np.abs(start - entry).max()
        if err > clip.get("pose_tolerance_deg", 2.0):
            raise ValueError(f"{ref(clip)}: start is {err:.1f} deg from entry pose; move there first")

    kfs = _timed_keyframes(clip, p["time_scale"], p["hold"], repeat)
    duration = max(k["t"] for k in kfs)
    dt = 1 / robot.rate
    t = np.arange(math.ceil(duration / dt - 1e-9) + 1) * dt

    q = np.tile(start, (len(t), 1))
    for name in clip["joint_mask"]:
        j = names.index(name)
        track = sorted((k["t"], k["joints"][name], k.get("ease", "ease_in_out")) for k in kfs if name in k["joints"])
        times = np.array([k[0] for k in track])
        values = np.array([k[1] for k in track], float)
        eases = [k[2] for k in track]
        if not additive:
            values[0] = start[j]  # absolute clips begin exactly at the actual start
        # Amplitude scales the motion around the straight line from first to last value,
        # so start and end (entry/exit, or "returns to start") are preserved.
        span = times[-1] - times[0]
        baseline = values[0] + (values[-1] - values[0]) * ((times - times[0]) / span if span > 0 else 0)
        values = baseline + p["amplitude"] * (values - baseline)
        q[:, j] = _interpolate(times, values, eases, t) + (start[j] if additive else 0)

    events = []
    for e in clip.get("events", []):
        for r in range(repeat):
            et = (e["t"] + r * clip["keyframes"][-1]["t"]) * p["time_scale"]
            events.append({**e, "t": et})
    return Trajectory(t, q, list(names), events, [(0.0, float(t[-1]), ref(clip))])


def move(robot, start, target, duration, ease="ease_in_out", label="move"):
    """Functional point-to-point move in joint space."""
    clip = {
        "name": label, "variant": "", "mode": "absolute", "joint_mask": robot.joint_names,
        "keyframes": [
            {"t": 0.0, "joints": dict(zip(robot.joint_names, map(float, start)))},
            {"t": duration, "joints": dict(zip(robot.joint_names, map(float, target))), "ease": ease},
        ],
    }
    traj = play(clip, robot, start=start, enforce_ranges=False)
    traj.marks = [(0.0, traj.duration, label)]
    return traj


def hold_pose(robot, pose, duration, label="hold"):
    return move(robot, pose, pose, duration, ease="linear", label=label)
